name: onekettled_bandit
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.12.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  wakelock_plus: ^1.2.8
  shared_preferences: ^2.2.3 # NEU: Für das Speichern deiner Wiederholungen

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bulgariansplitsquad.png
    - assets/clean.png
    - assets/deadbug.png
    - assets/einarmigesrudern.png
    - assets/floorpress.png
    - assets/gobletsquat.png
    - assets/highpull.png
    - assets/kettlebellsitup.png
    - assets/kettlebellswing.png
    - assets/overheadpress.png
    - assets/plankpullthrough.png
    - assets/plankrow.png
    - assets/pushpress.png
    - assets/quartergetup.png
    - assets/reverselunge.png
    - assets/romaniandeadlift.png
    - assets/russiantwist.png
    - assets/singlelegdeadlift.png
    - assets/staggeredrow.png
    - assets/suitcasecarry.png
    - assets/sumosquat.png
    - assets/turkishgetup.png
