name: Flutter Web zu GitHub Pages

on:
  push:
    branches: [ main, master ] # Startet, sobald du Code hochlädst

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Java einrichten
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter einrichten
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Abhängigkeiten laden
        run: flutter pub get

      - name: Web-App bauen
        run: flutter build web --base-href "/${{ github.event.repository.name }}/"

      - name: Zu GitHub Pages hochladen
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages # Hier wird die fertige Webseite abgelegt
